export const DESTINATIONS = {
  'East Asia': [
    { name: 'Tokyo', country: 'Japan', countryCode: 'jp' },
    { name: 'Seoul', country: 'South Korea', countryCode: 'kr' },
    { name: 'Beijing', country: 'China', countryCode: 'cn' },
    { name: 'Shanghai', country: 'China', countryCode: 'cn' },
    { name: 'Hong Kong', country: 'Hong Kong', countryCode: 'hk' },
  ],
  'South Asia': [
    { name: 'Mumbai', country: 'India', countryCode: 'in' },
    { name: 'Delhi', country: 'India', countryCode: 'in' },
    { name: 'Karachi', country: 'Pakistan', countryCode: 'pk' },
    { name: 'Dhaka', country: 'Bangladesh', countryCode: 'bd' },
    { name: 'Kolkata', country: 'India', countryCode: 'in' },
    { name: 'Bangkok', country: 'Thailand', countryCode: 'th' },
    { name: 'Singapore', country: 'Singapore', countryCode: 'sg' },
    { name: 'Kuala Lumpur', country: 'Malaysia', countryCode: 'my' },
    { name: 'Jakarta', country: 'Indonesia', countryCode: 'id' },
    { name: 'Ho Chi Minh City', country: 'Vietnam', countryCode: 'vn' },
  ],
  'West Asia': [
    { name: 'Dubai', country: 'United Arab Emirates', countryCode: 'ae' },
    { name: 'Istanbul', country: 'Turkey', countryCode: 'tr' },
    { name: 'Doha', country: 'Qatar', countryCode: 'qa' },
    { name: 'Riyadh', country: 'Saudi Arabia', countryCode: 'sa' },
    { name: 'Tel Aviv', country: 'Israel', countryCode: 'il' },
  ],
  'Western Europe': [
    { name: 'Paris', country: 'France', countryCode: 'fr' },
    { name: 'London', country: 'United Kingdom', countryCode: 'gb' },
    { name: 'Berlin', country: 'Germany', countryCode: 'de' },
    { name: 'Amsterdam', country: 'Netherlands', countryCode: 'nl' },
    { name: 'Brussels', country: 'Belgium', countryCode: 'be' },
  ],
  'Eastern Europe': [
    { name: 'Moscow', country: 'Russia', countryCode: 'ru' },
    { name: 'Prague', country: 'Czech Republic', countryCode: 'cz' },
    { name: 'Warsaw', country: 'Poland', countryCode: 'pl' },
    { name: 'Budapest', country: 'Hungary', countryCode: 'hu' },
    { name: 'Kyiv', country: 'Ukraine', countryCode: 'ua' },
  ],
  'Southern Europe': [
    { name: 'Rome', country: 'Italy', countryCode: 'it' },
    { name: 'Athens', country: 'Greece', countryCode: 'gr' },
    { name: 'Madrid', country: 'Spain', countryCode: 'es' },
    { name: 'Lisbon', country: 'Portugal', countryCode: 'pt' },
    { name: 'Barcelona', country: 'Spain', countryCode: 'es' },
  ],
  'Northern Europe': [
    { name: 'Stockholm', country: 'Sweden', countryCode: 'se' },
    { name: 'Copenhagen', country: 'Denmark', countryCode: 'dk' },
    { name: 'Oslo', country: 'Norway', countryCode: 'no' },
    { name: 'Helsinki', country: 'Finland', countryCode: 'fi' },
    { name: 'Reykjavik', country: 'Iceland', countryCode: 'is' },
  ],
  'North America': [
    { name: 'New York City', country: 'United States', countryCode: 'us' },
    { name: 'Los Angeles', country: 'United States', countryCode: 'us' },
    { name: 'San Diego', country: 'United States', countryCode: 'us' },
    { name: 'Toronto', country: 'Canada', countryCode: 'ca' },
    { name: 'Chicago', country: 'United States', countryCode: 'us' },
    { name: 'Houston', country: 'United States', countryCode: 'us' },
    { name: 'Montreal', country: 'Canada', countryCode: 'ca' },
    { name: 'Mexico City', country: 'Mexico', countryCode: 'mx' },
  ],
  'South America': [
    {
      displayName: 'São Paulo',
      name: 'Sao Paulo',
      country: 'Brazil',
      countryCode: 'br',
    },
    {
      displayName: 'Brasília',
      name: 'Brasilia',
      country: 'Brazil',
      countryCode: 'br',
    },
    { name: 'Buenos Aires', country: 'Argentina', countryCode: 'ar' },
    {
      displayName: 'Rio de Janeiro',
      name: 'Rio de Janeiro',
      country: 'Brazil',
      countryCode: 'br',
    },
    { name: 'Lima', country: 'Peru', countryCode: 'pe' },
    {
      displayName: 'Bogotá',
      name: 'Bogota',
      country: 'Colombia',
      countryCode: 'co',
    },
    { name: 'Santiago', country: 'Chile', countryCode: 'cl' },
  ],
  'Central America': [
    { name: 'Guatemala City', country: 'Guatemala', countryCode: 'gt' },
    { name: 'San Salvador', country: 'El Salvador', countryCode: 'sv' },
    { name: 'Panama City', country: 'Panama', countryCode: 'pa' },
    {
      displayName: 'San José',
      name: 'San Jose',
      country: 'Costa Rica',
      countryCode: 'cr',
    },
    { name: 'Villa Nueva', country: 'Guatemala', countryCode: 'gt' },
    { name: 'Tegucigalpa', country: 'Honduras', countryCode: 'hn' },
  ],
  Africa: [
    { name: 'Cairo', country: 'Egypt', countryCode: 'eg' },
    { name: 'Cape Town', country: 'South Africa', countryCode: 'za' },
    { name: 'Marrakech', country: 'Morocco', countryCode: 'ma' },
    { name: 'Nairobi', country: 'Kenya', countryCode: 'ke' },
    { name: 'Zanzibar City', country: 'Tanzania', countryCode: 'tz' },
    { name: 'Johannesburg', country: 'South Africa', countryCode: 'za' },
    { name: 'Lagos', country: 'Nigeria', countryCode: 'ng' },
    { name: 'Addis Ababa', country: 'Ethiopia', countryCode: 'et' },
    { name: 'Luanda', country: 'Angola', countryCode: 'ao' },
    { name: 'Accra', country: 'Ghana', countryCode: 'gh' },
  ],
}
