export const DESTINATIONS = {
  'East Asia': [
    { name: 'Tokyo', country: 'Japan' },
    { name: 'Seoul', country: 'South Korea' },
    { name: 'Beijing', country: 'China' },
    { name: 'Shanghai', country: 'China' },
    { name: 'Hong Kong', country: 'Hong Kong' },
  ],
  'South Asia': [
    { name: 'Mumbai', country: 'India' },
    { name: 'Delhi', country: 'India' },
    { name: 'Karachi', country: 'Pakistan' },
    { name: 'Dhaka', country: 'Bangladesh' },
    { name: 'Kolkata', country: 'India' },
    { name: 'Bangkok', country: 'Thailand' },
    { name: 'Singapore', country: 'Singapore' },
    { name: 'Kuala Lumpur', country: 'Malaysia' },
    { name: 'Jakarta', country: 'Indonesia' },
    { name: 'Ho Chi Minh City', country: 'Vietnam' },
  ],
  'West Asia': [
    { name: 'Dubai', country: 'United Arab Emirates' },
    { name: 'Istanbul', country: 'Turkey' },
    { name: 'Doha', country: 'Qatar' },
    { name: 'Riyadh', country: 'Saudi Arabia' },
    { name: 'Tel Aviv', country: 'Israel' },
  ],
  'Western Europe': [
    { name: 'Paris', country: 'France' },
    { name: 'London', country: 'United Kingdom' },
    { name: 'Berlin', country: 'Germany' },
    { name: 'Amsterdam', country: 'Netherlands' },
    { name: 'Brussels', country: 'Belgium' },
  ],
  'Eastern Europe': [
    { name: 'Moscow', country: 'Russia' },
    { name: 'Prague', country: 'Czech Republic' },
    { name: 'Warsaw', country: 'Poland' },
    { name: 'Budapest', country: 'Hungary' },
    { name: 'Kyiv', country: 'Ukraine' },
  ],
  'Southern Europe': [
    { name: 'Rome', country: 'Italy' },
    { name: 'Athens', country: 'Greece' },
    { name: 'Madrid', country: 'Spain' },
    { name: 'Lisbon', country: 'Portugal' },
    { name: 'Barcelona', country: 'Spain' },
  ],
  'Northern Europe': [
    { name: 'Stockholm', country: 'Sweden' },
    { name: 'Copenhagen', country: 'Denmark' },
    { name: 'Oslo', country: 'Norway' },
    { name: 'Helsinki', country: 'Finland' },
    { name: 'Reykjavik', country: 'Iceland' },
  ],
  'North America': [
    { name: 'New York City', country: 'United States' },
    { name: 'Los Angeles', country: 'United States' },
    { name: 'Toronto', country: 'Canada' },
    { name: 'Chicago', country: 'United States' },
    { name: 'Mexico City', country: 'Mexico' },
  ],
  'South America': [
    { name: 'Buenos Aires', country: 'Argentina' },
    { name: 'Rio de Janeiro', country: 'Brazil' },
    { name: 'Lima', country: 'Peru' },
    { name: 'Bogota', country: 'Colombia' },
    { name: 'Santiago', country: 'Chile' },
  ],
  Africa: [
    { name: 'Cairo', country: 'Egypt' },
    { name: 'Cape Town', country: 'South Africa' },
    { name: 'Marrakech', country: 'Morocco' },
    { name: 'Nairobi', country: 'Kenya' },
    { name: 'Zanzibar City', country: 'Tanzania' },
    { name: 'Johannesburg', country: 'South Africa' },
    { name: 'Lagos', country: 'Nigeria' },
    { name: 'Addis Ababa', country: 'Ethiopia' },
    { name: 'Luanda', country: 'Angola' },
    { name: 'Accra', country: 'Ghana' },
  ],
}
